### ISSUE TITLE
Plugin for #music

### ISSUE THREAD

**Issue by hreeder** [hreeder/botbot#13]
This is a major one, so I think we may want to delve into more issues for some of these bullet points

- [ ] Catalog Spotify Playlists
- [ ] Notify on changes to playlists
- [ ] Add to playlist
  - [ ] By spotify URI
  - [ ] From YouTube

I was considering using [Spotipy](http://spotipy.readthedocs.io/en/latest/) to communicate with the Spotify Web API.

**Comment by hreeder** [comment]
Once they accept the invites, this will also be assigned to @neanias by request

**Comment by neanias** [comment]
We're going to need API keys, also, all the playlists are probably going to show up on your account. It might be worth looking into making a '#music' playlist folder
