### ISSUE TITLE
Docstrings for commands

### ISSUE THREAD

**Issue by cazagen** [hreeder/botbot#22]
The following is a list of commands that don't have any docstring:
- [ ] broadcasts.py
- [x] Bunny command in bunny.py
- [x] buttmaster.py
- [x] cats.py
- [x] dogs.py
- [x] excuses.py
- [x] giphy.py
- [x] Some of internals.py
- [x] shipit.py

**Comment by neanias** [comment]
@hreeder I'm leaving the broadcasts.py to you, since it's one of yours

**Comment by neanias** [comment]
Just `broadcasts.py` left now
