### ISSUE TITLE
Be able to transfer karma/butts from one user to another

### ISSUE THREAD

**Issue by himmelmaus** [hreeder/botbot#42]
I've been mucking about with a command to transfer karma from one user to another, so if somebody changes their nickname (i.e. dunx -> duncanguthrie) it can be transferred. I'd make this so only the bot owner was able to execute the command or we'd have karma privacy - but what's the opinion on this sort of command/what should it be called? I was thinking `$transfer name1 name2` or 
`$alias name1 name2`

**Comment by cazagen** [comment]
I like the idea of being able transfer karma. However I also quite like the idea of users having aliases that are linked. So in duncan's case dunx++ would also increment yulax behind the scenes

**Comment by neanias** [comment]
We already use something vaguely similar for the `np` command

**Comment by himmelmaus** [comment]
I thought about doing that, but that also has the problem of if somebody at a later point joins with the same username.

I'll stick with my current method of approach and send a pr sometime soon

**Comment by neanias** [comment]
I think Findlay's right, I think it better to transfer them over to the new nick in redis. The thing to be wary of is if the user transfers nicks but then is awarded karma before transferring their old nick's karma.

**Comment by himmelmaus** [comment]
@neanias I don't see the issue there ?

**Comment by neanias** [comment]
Do we combine their old karma and new karma or just plain overwrite it?

**Comment by cazagen** [comment]
@neanias yeah that's a fair point

**Comment by himmelmaus** [comment]
oh, I was planning of having `user2's karma = user1's karma + user2's karma` and then just resetting user1's karma to 0 - and doing the same thing with the butts

so basically combining the 2 karmas then resetting the other's to 0

**Comment by neanias** [comment]
I wouldn't reset user1; just plain wipe it. The internals handles non-existing keys

**Comment by himmelmaus** [comment]
@neanias good point

I've also realised there's a problem with karma terms where there's a space within the name - shall I assume this is only going to be used for transferring karma between _users_ and hence none of the names should have spaces in them?

**Comment by neanias** [comment]
I wouldn't assume that. I'd make sure it works for all karma terms.

**Comment by himmelmaus** [comment]
but that's haaaaard

**Comment by himmelmaus** [comment]
i.e. I can't think how the user would separate the terms

**Comment by neanias** [comment]
`$transfer "hello there" "general kenobi"`

**Comment by neanias** [comment]
God gave us regex for this.

**Comment by neanias** [comment]
Make sure you differentiate the two usages in the docstring though. `$transfer <old> <new> or $transfer "<old with spaces>" "<new (with/out spaces)>"`. That's a fun one, actually. Supporting moving from non-spaced to spaced names and vice-versa.

**Comment by hreeder** [comment]
I’ve often wondered if you could subdue argparse into parsing commands from botbot, that could be an idea rather than building our own tokeniser

As for exact command, let me have a think

________________________________

**Comment by himmelmaus** [comment]
when parsing args how does botbot interpret " and ', I take it they become \\" and \\' ?

**Comment by himmelmaus** [comment]
ok I've sent a pr with my first rough attempt at this [here](https://github.com/findoslice/botbot/blob/master/ircbot/plugins/transfer.py) , will attempt adding the tokeniser once I've had my tea

**Comment by himmelmaus** [comment]
Ok so I've got tokenisation working using regex, however since I'm also transferring butts should I make the butt part not transfer anything if there's a space in the name?
