### ISSUE TITLE
Consider migrating to Pipenv

### ISSUE THREAD

**Issue by neanias** [hreeder/botbot#46]
I know that this obviously works, but Pipenv would be a cleaner solution, given its tighter support for `pyenv` and `virtualenv`s.

**Comment by hreeder** [comment]
I’d love to learn how to Pipenv so this would be pretty cool to see done!

**Comment by neanias** [comment]
I'm happy to do it and show you, if you'd like?

**Comment by hreeder** [comment]
That’d be cool, yeah!

**Comment by neanias** [comment]
Cool, remind me this weekend, and I'll sort it out

**Comment by neanias** [comment]
@hreeder, do we have any particular dependencies that need version locking? Pipenv encourages leaving them open in the `Pipfile` and letting the `Pipfile.lock` handle the versioning.

**Comment by neanias** [comment]
Fixed by #47
